### ISSUE TITLE
【Bug】idea eap最新版本出错

### ISSUE THREAD

**Issue by liuyike233** [tuchg/ChinesePinyin-CodeCompletionHelper#36]
## 请事先检查下列事项

- [ x ]  已了解或使用过本项目
- [ x ]  issue/feature 尚未有前人提出

## 编程语言
android-java
## 预期表现
汉语补全
## 当前表现
不能提示方法名
## 可能的解决方案
不知道

## 重现错误场景
idea eap版本,按下.就报错,不能提示方法
> 提供代码片段或截图
`
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	 com.intellij.openapi.util.text.StringUtil.difference(StringUtil.java:395)
	 com.github.tuchg.nonasciicodecompletionhelper.extensions.ChineseCompletionContributor$fillCompletionVariants$1.consume(ChineseCompletionContributor.kt:56)
	 com.github.tuchg.nonasciicodecompletionhelper.extensions.ChineseCompletionContributor$fillCompletionVariants$1.consume(ChineseCompletionContributor.kt:19)
	 com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:167)
	 com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:154)
	 com.intellij.codeInsight.completion.CompletionResultSet.passResult(CompletionResultSet.java:57)
	 org.jetbrains.android.AndroidJavaCompletionContributor.lambda$fillCompletionVariants$1(AndroidJavaCompletionContributor.java:73)
	 com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:167)
	 com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:154)
	 com.intellij.codeInsight.completion.CompletionResultSet.passResult(CompletionResultSet.java:57)
	 com.intellij.codeInsight.completion.JavaNoVariantsDelegator$ResultTracker.consume(JavaNoVariantsDelegator.java:247)
	at com.intellij.codeInsight.completion.JavaNoVariantsDelegator$1.consume(JavaNoVariantsDelegator.java:51)
	at com.intellij.codeInsight.completion.JavaNoVariantsDelegator$1.consume(JavaNoVariantsDelegator.java:48)
	at com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:167)
	at com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.passResult(CompletionResultSet.java:57)
	at com.intellij.codeInsight.completion.JShellCompletionContributor.lambda$fillCompletionVariants$0(JShellCompletionContributor.java:30)
	at com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:167)
	at com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.passResult(CompletionResultSet.java:57)
	at com.intellij.codeInsight.completion.BaseCompletionService$BaseCompletionResultSet.addElement(BaseCompletionService.java:119)
	at com.intellij.codeInsight.completion.CompletionResultSet.addAllElements(CompletionResultSet.java:87)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl$CompletionResultSetImpl.lambda$addAllElements$0(CompletionServiceImpl.java:102)
	at com.intellij.codeInsight.completion.CompletionThreadingBase.withBatchUpdate(CompletionThreadingBase.java:33)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl$CompletionResultSetImpl.addAllElements(CompletionServiceImpl.java:102)
	at com.intellij.codeInsight.completion.JavaCompletionSession.flushBatchItems(JavaCompletionSession.java:46)
	at com.intellij.codeInsight.completion.JavaCompletionContributor.fillCompletionVariants(JavaCompletionContributor.java:344)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:78)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.completion.JShellCompletionContributor.fillCompletionVariants(JShellCompletionContributor.java:28)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:78)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.completion.JavaNoVariantsDelegator.fillCompletionVariants(JavaNoVariantsDelegator.java:59)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:78)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at org.jetbrains.android.AndroidJavaCompletionContributor.fillCompletionVariants(AndroidJavaCompletionContributor.java:60)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:78)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.github.tuchg.nonasciicodecompletionhelper.extensions.ChineseCompletionContributor.fillCompletionVariants(ChineseCompletionContributor.kt:35)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:78)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:89)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:32)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:78)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:61)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:134)
	at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.java:41)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$calculateItems$12(CompletionProgressIndicator.java:862)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:162)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:574)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:161)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:858)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:846)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:353)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1097)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:345)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util..FutureTask.run(FutureTask.java:264)
	 java.base/java.util..ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	 java.base/java.util..ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	 java.base/java.util..Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	 java.base/java.util..Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	 java.base/java.security.AccessController.doPrivileged(Native Method)
	 java.base/java.util..Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	 java.base/java.lang.Thread.run(Thread.java:834)
`

## 使用环境
macos bigsur 11.2
* 插件版本:
* IDE版本（如 IDEA 2020.2）: eap最新版
* 操作系统版本（如 Mac OS 10.15.6）: macos 11.2

**Comment by tuchg** [comment]
已修复，补全功能并无异常，仅输入.时出现异常
